bind=SUPER,e,spawn,nautilus --new-window
bind=SUPER+SHIFT,n,spawn,gnome-text-editor --new-window
bind=SUPER+SHIFT,return,spawn,emacsclient -c -a 'emacs'

bind=SUPER,b,spawn,org.mozilla.firefox
bind=SUPER+SHIFT,b,spawn,app.zen_browser.zen
bind=SUPER+Ctrl,b,spawn,helium

bind=CTRL+SHIFT,Escape,spawn,gnome-system-monitor
bind=CTRL+ALT,Delete,spawn,gnome-system-monitor
bind=SUPER,Delete,spawn,missioncenter

bind=NONE,XF86Favorites,spawn,gnome-calculator
bind=Shift,XF86Favorites,spawn,qalculate-gtk

bind=NONE,Print,spawn,flameshot gui
bind=SHIFT,Print,spawn,flameshot gui --last-region
bind=CTRL,Print,spawn,flameshot screen
bind=CTRL+SHIFT,Print,spawn,flameshot full

bind=SUPER,Print,spawn,com.github.tenderowl.frog
bind=ALT,Print,spawn,art.fatdawlf.Piccolo

# bind=SUPER+SHIFT,V,spawn,gnome-characters

# bind=SUPER,m,spawn,com.rtosta.zapzap
bind=SUPER,m,toggle_named_scratchpad,com.rtosta.zapzap,none,com.rtosta.zapzap

# bind=SUPER,a,spawn,com.super_productivity.SuperProductivity
bind=SUPER,a,toggle_named_scratchpad,com.super_productivity.SuperProductivity,none,com.super_productivity.SuperProductivity

# bind=SUPER,c,spawn,gnome-calendar
bind=SUPER,c,toggle_named_scratchpad,org.gnome.Calendar,none,gnome-calendar

# Script para poner rayas
bind=SUPER+ALT,Minus,spawn,~/.config/mango/scripts/raya
