bind=SUPER,e,spawn,nautilus --new-window
bind=SUPER+SHIFT,n,spawn,gnome-text-editor --new-window
bind=SUPER+SHIFT,return,spawn,emacsclient -c -a 'emacs'

bind=SUPER,m,spawn,zapzap
bind=SUPER,b,spawn,org.mozilla.firefox
bind=SUPER+SHIFT,b,spawn,app.zen_browser.zen
bind=SUPER+Ctrl,b,spawn,helium

bind=NONE,XF86Favorites,spawn,gnome-calculator
bind=Shift,XF86Favorites,spawn,qalculate-gtk

bind=CTRL+SHIFT,Escape,spawn,gnome-system-monitor
bind=CTRL+ALT,Delete,spawn,gnome-system-monitor
bind=SUPER,Delete,spawn,missioncenter

bind=SUPER+SHIFT,V,spawn,gnome-characters
