# Volumen mediante PipeWire & WirePlumber.
# '-l 1.0' limita el volumen al 100%
# -------------------------------------------
bindl=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.02+ -l 1.0
bindl=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.02-
bindl=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl=NONE,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Control de medios mediante playerctl.
bindl=NONE,XF86AudioPlay,spawn,playerctl play-pause
bindl=NONE,XF86AudioStop,spawn,playerctl stop
bindl=NONE,XF86AudioPrev,spawn,playerctl previous
bindl=NONE,XF86AudioNext,spawn,playerctl next

# Por acá replico el control de medios
# pero con las teclas de mi ThinkPad
bindl=NONE,XF86NotificationCenter,spawn,playerctl play-pause
bindl=NONE,XF86PickupPhone,spawn,playerctl previous
bindl=NONE,XF86HangupPhone,spawn,playerctl next

# Controlar el brillo mediante brightnessctl.
bindl=NONE,XF86MonBrightnessUp,spawn,brightnessctl --class=backlight set +5%
bindl=NONE,XF86MonBrightnessDown,spawn,brightnessctl --class=backlight set 5%-

# USO DE GESTOS TRACKPAD
gesturebind=none,left,4,spawn,playerctl previous
gesturebind=none,right,4,spawn,playerctl next
gesturebind=none,up,4,spawn,playerctl play-pause
gesturebind=none,down,4,spawn,playerctl play-pause
