bind=SUPER,d,spawn,noctalia msg panel-toggle launcher
bind=SUPER,s,spawn,noctalia msg panel-toggle control-center
bind=SUPER,x,spawn,noctalia msg panel-toggle session
bind=SUPER,v,spawn,noctalia msg panel-toggle clipboard

bind=SUPER+CTRL,l,spawn,noctalia msg session lock
bind=SUPER+CTRL+SHIFT,l,spawn,noctalia msg session lock-and-suspend
bind=SUPER+SHIFT,comma,spawn,noctalia msg settings-toggle

# bindl=NONE,XF86AudioRaiseVolume,spawn,noctalia msg volume-up
# bindl=NONE,XF86AudioLowerVolume,spawn,noctalia msg volume-down
# bindl=NONE,XF86AudioMute,spawn,noctalia msg volume-mute
# bindl=NONE,XF86MonBrightnessUp,spawn,noctalia msg brightness-up
# bindl=NONE,XF86MonBrightnessDown,spawn,noctalia msg brightness-down

# PLUGINS
bind=SUPER,n,spawn,noctalia msg panel-toggle noctalia/notes:panel
