bind=SUPER,e,spawn,nautilus --new-window
bind=SUPER+SHIFT,n,spawn,gnome-text-editor --new-window
bind=SUPER+SHIFT,return,spawn,emacsclient -c -a 'emacs'

bind=SUPER+SHIFT,V,spawn,gnome-characters

bind=CTRL+SHIFT,Escape,spawn,gnome-system-monitor
bind=CTRL+ALT,Delete,spawn,gnome-system-monitor
bind=SUPER,Delete,spawn,missioncenter

bind=NONE,XF86Favorites,spawn,gnome-calculator
bind=Shift,XF86Favorites,spawn,qalculate-gtk

bind=NONE,Print,spawn,flameshot gui
bind=SHIFT,Print,spawn,flameshot gui --last-region
bind=CTRL,Print,spawn,flameshot screen
bind=CTRL+SHIFT,Print,spawn,flameshot full

# bind=SUPER,m,spawn,zapzap
bind=SUPER,m,toggle_named_scratchpad,com.rtosta.zapzap,none,zapzap

# bind=SUPER+SHIFT,m,spawn,com.super_productivity.SuperProductivity
bind=SUPER+SHIFT,m,toggle_named_scratchpad,com.super_productivity.SuperProductivity,none,com.super_productivity.SuperProductivity

bind=SUPER,b,spawn,org.mozilla.firefox
bind=SUPER+SHIFT,b,spawn,app.zen_browser.zen
bind=SUPER+Ctrl,b,spawn,helium
