# ============================== Flotar ventanas ==============================

windowrule=isfloating:1,appid:org.gnome.NautilusPreviewer
windowrule=isfloating:1,appid:org.gnome.Nautilus,title:Open video file
windowrule=isfloating:1,appid:org.gnome.Nautilus,title:^Añadir archivos de vídeo
windowrule=isfloating:1,appid:org.gnome.Nautilus,title:Archivos
windowrule=isfloating:1,appid:org.gnome.Nautilus,title:Abrir una carpeta como bóveda
windowrule=isfloating:1,title:Abrir archivo
windowrule=isfloating:1,title:Open file
windowrule=isfloating:1,appid:Upscayl,title:Select Image

windowrule=isfloating:1,appid:org.inkscape.Inkscape,title:importación
windowrule=isfloating:1,appid:org.inkscape.Inkscape,title:Entrada SVG
windowrule=isfloating:1,appid:org.inkscape.Inkscape,title:Sombra paralela
windowrule=isfloating:1,appid:org.inkscape.Inkscape,title:archivos
windowrule=isfloating:1,appid:import_web_image.py # de inkscape

windowrule=isfloating:1,appid:resolve
# windowrule=isfloating:1,appid:resolve,title:resolve
# windowrule=isfloating:1,appid:resolve,title:Organizador de proyectos
# windowrule=isfloating:1,appid:resolve,title:^Crear
windowrule=isfloating:1,appid:org.kde.kdenlive,title:Splash Screen — Kdenlive

windowrule=isfloating:1,title:Configuración # de Flameshot
windowrule=isfloating:1,title:Package Installation # MiKTeX

windowrule=isfloating:1,appid:org.gnome.Characters
windowrule=isfloating:1,appid:com.github.finefindus.eyedropper
windowrule=isfloating:1,appid:art.fatdawlf.Piccolo
windowrule=isfloating:1,appid:com.github.tenderowl.frog
windowrule=isfloating:1,appid:io.github.focustimerhq.FocusTimer

windowrule=isfloating:1,appid:org.gnome.Calculator
windowrule=isfloating:1,appid:qalculate-gtk
windowrule=isfloating:1,appid:app.drey.Dialect
windowrule=isfloating:1,appid:de.haeckerfelix.Shortwave
windowrule=isfloating:1,appid:org.gnome.Meld


# ====== Flotar con cierto tamaño ======

windowrule=isfloating:1,width:1200,height:800,appid:org.gnome.SystemMonitor
windowrule=isfloating:1,width:1200,height:800,appid:missioncenter
windowrule=isfloating:1,width:1000,height:780,appid:org.kde.easyeffects
windowrule=isfloating:1,width:960,height:770,appid:bitwarden
# windowrule=isfloating:1,width:480,height:390,appid:org.gnome.TextEditor


# ====== Scratchpads ======

# Zapzap
# windowrule=isfloating:1,width:1128,height:786,appid:com.rtosta.zapzap
windowrule=isnamedscratchpad:1,width:1128,height:786,appid:com.rtosta.zapzap

# Super Productivity
# windowrule=isfloating:1,width:1250,height:850,appid:com.super_productivity.SuperProductivity
windowrule=isnamedscratchpad:1,width:1250,height:850,appid:com.super_productivity.SuperProductivity

# Gnome Calendar
# windowrule=isfloating:1,width:1380,height:915,appid:org.gnome.Calendar
windowrule=isnamedscratchpad:1,width:1380,height:915,appid:org.gnome.Calendar


# ============================== Picture in picture ==============================

windowrule=isfloating:1,isglobal:1,isnoanimation:1,appid:firefox$,title:^Picture-in-Picture$
windowrule=isfloating:1,isglobal:1,isnoanimation:1,appid:app.zen_browser.zen,title:Picture-in-Picture

# Mini reproductor de Spotify
windowrule=isfloating:1,isglobal:1,isnoanimation:1,width:300,height:300,appid:chromium-browser


# ============================== Juegos en pantalla completa ==============================

windowrule=isfullscreen:1,appid:dontstarve_steam_x64
windowrule=isfullscreen:1,appid:FEZ.bin.x86_64
